# Generated by Django 5.0.7 on 2024-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceData',
        ),
    ]
